
modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="better_rubber"
version="1.20.1-1.0.4"
displayName="Better Rubber"
logoFile="better_rubber.png"
authors="Lemon_Juiced & Scalar Team"

description='''
Makes rubber and plastic much easier to attain for any tech mods.
'''

[[dependencies.better_rubber]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_rubber]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
